services:
  reverse:
    image: nginx:stable-alpine
    container_name: reverse
    hostname: reverse
    restart: always
    extra_hosts:
      - "host.docker.internal=host-gateway"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf:ro"
      - "./locations:/etc/nginx/locations:ro"
      - "./configuration:/etc/nginx/configuration:ro"
      - "./sites-enabled:/etc/nginx/sites-enabled:ro"
      - "./error-pages:/etc/nginx/error-pages/"
      - "./resources:/var/www/html/resources"
      - "./ssl:/etc/nginx/ssl"
      - "./logs:/var/log/nginx/"
    networks:
      local_net: {}
    ports:
      - 80:80
      - 443:443
      - 60180:60180
      - 60280:60280
      - 60380:60380
      - 60480:60480
      - 64443:64443

networks:
  local_net:
    external: true
    driver: bridge
    name: services
